### ISSUE TITLE
Listen to einvoice-send/inChannelConfig events and export supplier data to FTP

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/a2a-integration#1]
listen to 
inChannelConfig.created
inChannelConfig.updated

if status is 'approved':
take inChannelConfig from event
use supplierId to make API call to supplier and get master record and bank accounts

then
create flat file (CSV, semicolon as separator)
|| supplierId || supplierName || vatIdentNo || commercialRegisterNo || cityOfRegistration || vatIdentificationNo || globalLocationNo || dunsNo || status || 
Supplier row (exactly one)

|| supplierId || accountNumber (IBAN) || bankIdentificationCode (BIC) || swiftCode || bankCode || bankName ||
bank account rows (one per account)

|| supplierId || type || name1 || name2 || name3 || street || zipCode || city || poboxZipCode || pobox || countryId ||
address rows (one per address)

then
upload to FTP

add consul keys for ftp endpoint address, protocol, folder etc.

**Comment by lasong** [comment]
Done
