### ISSUE TITLE
Invoice Tranfer: Copy Attachments to a2a

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/a2a-integration#8]
When saving a sales-invoice in the sales-invoice service, we generate Invoice-PDFs, too.
This PDF (and potentially other attachements) will be part of the Invoice JSON object - as described in #4.

Please assure that you copy the files (usually stored on our blob server) to the FTP server.

**Comment by nczeranka** [comment]
see OpusCapita/sales-invoice/issues/33

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/a2a-integration/pull/10

**Comment by nczeranka** [comment]
No really. #10 implemented the copy of the invoice pdf from the blob, defined by the invoice key.
We will need a copy of the attachments as soon as we allow to upload pdfs for mapping.
